version: "3"
services:
  config:
    # replace username/repo:tag with your name and image details
    image: sudiptobasak/gateway:latest
    container_name: gateway
    hostname: gateway-host
    build: .
    environment:
      - HOST_HOSTNAME=${HOST_HOSTNAME}
      - HOST_IP=${HOST_IP}
      - DISCOVERY_HOST=${DISCOVERY_HOST}
      - DISCOVERY_PORT=${DISCOVERY_PORT}
    extra_hosts:
      - "${HOST_HOSTNAME}:${HOST_IP}"
#      - "${DISCOVERY_HOST}:${DISCOVERY_IP}"
    ports:
      - "9090:9090"
#    deploy:
#      replicas: 3
#      restart_policy:
#        condition: on-failure
#      resources:
#        limits:
#          cpus: "0.3"
#          memory: 300M
    networks:
      - default
networks:
  default:
    external:
      name: my-net
