version: "3"
services:
  config:
    # replace username/repo:tag with your name and image details
    image: sudiptobasak/config:latest
    container_name: config
    hostname: config-host
    build: .
    environment:
      - HOST_HOSTNAME=${HOST_HOSTNAME}
      - HOST_IP=${HOST_IP}
      - DISCOVERY_IP=${DISCOVERY_IP}
      - DISCOVERY_PORT=${DISCOVERY_PORT}
    extra_hosts:
      - "${HOST_HOSTNAME}:${HOST_IP}"
#      - "${DISCOVERY_HOST}:${DISCOVERY_IP}"
    ports:
      - "8081:8081"
#    deploy:
#      replicas: 3
#      restart_policy:
#        condition: on-failure
#      resources:
#        limits:
#          cpus: "0.3"
#          memory: 300M
    networks:
      - default
networks:
  default:
    external:
      name: my-net
